#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : wiredtiger
Version  : 2.7.0
Release  : 9
URL      : http://source.wiredtiger.com/releases/wiredtiger-2.7.0.tar.bz2
Source0  : http://source.wiredtiger.com/releases/wiredtiger-2.7.0.tar.bz2
Summary  : Extensions to the Python standard library unit testing framework
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause GPL-2.0 GPL-3.0 MIT
Requires: wiredtiger-bin
Requires: wiredtiger-doc
BuildRequires : bzip2-dev
BuildRequires : gperftools-dev
BuildRequires : lz4-dev
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pkgconfig(zlib)
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : scons
BuildRequires : setuptools
BuildRequires : snappy-dev

%description
WiredTiger is a data storage engine that provides APIs for efficiently
storing data in highly concurrent applications. It includes functionality
for automatically maintaining indexes. It implements both row and column
store formats - so that all types of data can be stored space efficiently.

WiredTiger is a library that can be accessed via C, Python and Java APIs.

%package bin
Summary: bin components for the wiredtiger package.
Group: Binaries

%description bin
bin components for the wiredtiger package.


%package dev
Summary: dev components for the wiredtiger package.
Group: Development
Requires: wiredtiger-bin
Provides: wiredtiger-devel

%description dev
dev components for the wiredtiger package.


%package doc
Summary: doc components for the wiredtiger package.
Group: Documentation

%description doc
doc components for the wiredtiger package.


%prep
%setup -q -n wiredtiger-2.7.0

%build
%configure --disable-static --enable-bzip2 \
--enable-lz4 \
--enable-tcmalloc \
--with-builtins=snappy,zlib
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/wt

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man3/*
